name: Continuous Integration

on:
  - push
  - pull_request


jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Rust formatting check
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce rust formatting
        run: cargo fmt --check
